export type ProductType = {
  id: number;
  type: 'PHONE' | 'WEARABLE' | 'AUDIO';
  brand: 'APPLE' | 'HUAWEI' | 'OPPO' | 'REALME' | 'VIVO' | 'XIAOMI';
  imgSrc: string;
  name: string;
  labels: string[];
  price: number;
  originalPrice: number | null;
}[];

export const products: ProductType = [
  {
    id: 1,
    type: 'PHONE',
    brand: 'VIVO',
    imgSrc: '/img/products/phones/vivo-x60.png',
    name: 'vivo X60',
    labels: ['Hot', 'New', '10% OFF'],
    price: 2520,
    originalPrice: 2799,
  },
  {
    id: 2,
    type: 'PHONE',
    brand: 'APPLE',
    imgSrc: '/img/products/phones/iphone-12-pro-max.png',
    name: 'iPhone 12 Pro Max',
    labels: ['Hot', 'New', '8% OFF'],
    price: 4899,
    originalPrice: 5299,
  },
  {
    id: 3,
    type: 'PHONE',
    brand: 'OPPO',
    imgSrc: '/img/products/phones/oppo-find-x3-pro.png',
    name: 'OPPO Find X3 Pro',
    labels: ['Hot', 'New', '5% OFF'],
    price: 4099,
    originalPrice: 4299,
  },
  {
    id: 4,
    type: 'PHONE',
    brand: 'HUAWEI',
    imgSrc: '/img/products/phones/huawei-mate-40-pro.png',
    name: 'HUAWEI Mate 40 Pro',
    labels: ['Hot', '7% OFF'],
    price: 3999,
    originalPrice: 4299,
  },
  {
    id: 5,
    type: 'WEARABLE',
    brand: 'OPPO',
    imgSrc: '/img/products/wearables/oppo-watch-46mm.png',
    name: 'OPPO Watch 46mm',
    labels: ['Hot', '23% OFF'],
    price: 999,
    originalPrice: 1299,
  },
  {
    id: 6,
    type: 'AUDIO',
    brand: 'VIVO',
    imgSrc: '/img/products/audio/vivo-tws-neo.png',
    name: 'vivo TWS neo',
    labels: ['Hot', '6% OFF'],
    price: 395,
    originalPrice: 420,
  },
  {
    id: 7,
    type: 'PHONE',
    brand: 'XIAOMI',
    imgSrc: '/img/products/phones/mi-11-ultra.png',
    name: 'Mi 11 Ultra',
    labels: ['Hot', '3% OFF'],
    price: 4649,
    originalPrice: 4799,
  },
  {
    id: 8,
    type: 'AUDIO',
    brand: 'OPPO',
    imgSrc: '/img/products/audio/oppo-enco-buds.png',
    name: 'OPPO Enco Buds',
    labels: ['Hot', '10% OFF'],
    price: 89,
    originalPrice: 99,
  },
  {
    id: 9,
    type: 'PHONE',
    brand: 'HUAWEI',
    imgSrc: '/img/products/phones/huawei-p40-pro-plus.png',
    name: 'HUAWEI P40 Pro Plus',
    labels: ['New', '5% OFF'],
    price: 4749,
    originalPrice: 4999,
  },
  {
    id: 10,
    type: 'PHONE',
    brand: 'OPPO',
    imgSrc: '/img/products/phones/oppo-reno5-f.png',
    name: 'OPPO Reno5 F',
    labels: ['New', '8% OFF'],
    price: 1099,
    originalPrice: 1199,
  },
  {
    id: 11,
    type: 'PHONE',
    brand: 'REALME',
    imgSrc: '/img/products/phones/realme-x7-pro-5g.png',
    name: 'realme X7 Pro 5G',
    labels: ['New', '10% OFF'],
    price: 1999,
    originalPrice: 2199,
  },
  {
    id: 12,
    type: 'WEARABLE',
    brand: 'HUAWEI',
    imgSrc: '/img/products/wearables/huawei-watch-3.png',
    name: 'HUAWEI Watch 3',
    labels: ['New', '10% OFF'],
    price: 1529,
    originalPrice: 1699,
  },
  {
    id: 13,
    type: 'PHONE',
    brand: 'OPPO',
    imgSrc: '/img/products/phones/oppo-find-x2.png',
    name: 'OPPO Find X2',
    labels: ['New', '4% OFF'],
    price: 3849,
    originalPrice: 3999,
  },
  {
    id: 14,
    type: 'PHONE',
    brand: 'APPLE',
    imgSrc: '/img/products/phones/iphone-12.png',
    name: 'iPhone 12',
    labels: ['Limited Stock', '8% OFF'],
    price: 3599,
    originalPrice: 3899,
  },
  {
    id: 15,
    type: 'WEARABLE',
    brand: 'REALME',
    imgSrc: '/img/products/wearables/realme-watch-2-pro.png',
    name: 'realme Watch 2 Pro',
    labels: ['Limited Stock', '9% OFF'],
    price: 272,
    originalPrice: 299,
  },
  {
    id: 16,
    type: 'PHONE',
    brand: 'VIVO',
    imgSrc: '/img/products/phones/vivo-v20-pro.png',
    name: 'vivo V20 Pro',
    labels: ['Limited Stock', '6% OFF'],
    price: 1785,
    originalPrice: 1899,
  },
  {
    id: 17,
    type: 'PHONE',
    brand: 'XIAOMI',
    imgSrc: '/img/products/phones/redmi-note-10-5g.png',
    name: 'Redmi Note 10 5G',
    labels: ['12% OFF'],
    price: 750,
    originalPrice: 850,
  },
  {
    id: 18,
    type: 'AUDIO',
    brand: 'REALME',
    imgSrc: '/img/products/audio/realme-buds-q2.png',
    name: 'realme Buds Q2',
    labels: ['8% OFF'],
    price: 129,
    originalPrice: 140,
  },
  {
    id: 19,
    type: 'WEARABLE',
    brand: 'REALME',
    imgSrc: '/img/products/wearables/realme-watch-2.png',
    name: 'realme Watch 2',
    labels: ['5% OFF'],
    price: 217,
    originalPrice: 229,
  },
  {
    id: 20,
    type: 'WEARABLE',
    brand: 'HUAWEI',
    imgSrc: '/img/products/wearables/huawei-watch-gt2.png',
    name: 'HUAWEI Watch GT2',
    labels: ['10% OFF'],
    price: 899,
    originalPrice: 999,
  },
  {
    id: 21,
    type: 'AUDIO',
    brand: 'OPPO',
    imgSrc: '/img/products/audio/oppo-enco-w31.png',
    name: 'OPPO Enco W31',
    labels: ['7% OFF'],
    price: 160,
    originalPrice: 172,
  },
  {
    id: 22,
    type: 'AUDIO',
    brand: 'HUAWEI',
    imgSrc: '/img/products/audio/huawei-freebuds-4.png',
    name: 'HUAWEI FreeBuds 4',
    labels: ['8% OFF'],
    price: 599,
    originalPrice: 650,
  },
  {
    id: 23,
    type: 'AUDIO',
    brand: 'REALME',
    imgSrc: '/img/products/audio/realme-buds-air-pro.png',
    name: 'realme Buds Air Pro',
    labels: ['5% OFF'],
    price: 369,
    originalPrice: 388,
  },
  {
    id: 24,
    type: 'WEARABLE',
    brand: 'APPLE',
    imgSrc: '/img/products/wearables/apple-watch-series-6.png',
    name: 'Apple Watch Series 6',
    labels: ['3% OFF'],
    price: 1749,
    originalPrice: 1800,
  },
  {
    id: 25,
    type: 'PHONE',
    brand: 'VIVO',
    imgSrc: '/img/products/phones/vivo-v50.png',
    name: 'vivo V50',
    labels: ['5% OFF'],
    price: 999,
    originalPrice: 1049,
  },
  {
    id: 26,
    type: 'AUDIO',
    brand: 'HUAWEI',
    imgSrc: '/img/products/audio/huawei-freebuds-4i.png',
    name: 'HUAWEI FreeBuds 4i',
    labels: ['8% OFF'],
    price: 379,
    originalPrice: 412,
  },
  {
    id: 27,
    type: 'AUDIO',
    brand: 'OPPO',
    imgSrc: '/img/products/audio/oppo-enco-x.png',
    name: 'OPPO Enco X',
    labels: ['13% OFF'],
    price: 488,
    originalPrice: 561,
  },
];
